// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6pwGgfDtvHS1X5sb2ztcs9Ndw9AtwABA',
    appId: '1:1007733277291:web:79b06238493375bb6fe72e',
    messagingSenderId: '1007733277291',
    projectId: 'vivatech-ed428',
    authDomain: 'vivatech-ed428.firebaseapp.com',
    storageBucket: 'vivatech-ed428.appspot.com',
    measurementId: 'G-M003XJKYGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEA50dX3DkMBoZBPZrpnMJom1aagMEAoI',
    appId: '1:1007733277291:android:509d5e4ab18e7f946fe72e',
    messagingSenderId: '1007733277291',
    projectId: 'vivatech-ed428',
    storageBucket: 'vivatech-ed428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBih4eGp-NYHvTF66VdQCOHF0ofWns3ADA',
    appId: '1:1007733277291:ios:c840ff79c1fd14936fe72e',
    messagingSenderId: '1007733277291',
    projectId: 'vivatech-ed428',
    storageBucket: 'vivatech-ed428.appspot.com',
    iosClientId: '1007733277291-lf64ljgvl35k4jkfimqlpie6ivre9d2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivatech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBih4eGp-NYHvTF66VdQCOHF0ofWns3ADA',
    appId: '1:1007733277291:ios:c840ff79c1fd14936fe72e',
    messagingSenderId: '1007733277291',
    projectId: 'vivatech-ed428',
    storageBucket: 'vivatech-ed428.appspot.com',
    iosClientId: '1007733277291-lf64ljgvl35k4jkfimqlpie6ivre9d2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivatech',
  );
}
